services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
    command: ["mongod", "--auth", "--bind_ip_all"]
    healthcheck:
      test:
        - CMD
        - mongosh
        - "mongodb://localhost:27017/admin"
        - "--eval=db.runCommand({ping:1})"
      retries: 3
      timeout: 5s
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://user:root@mongodb:27017/db?authSource=admin
    command: sh -c "npx ts-node src/seeders/product.seeder.ts && npm run start"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mongodb_network
  nginx:
    build:
      context: ./fe
      dockerfile: Dockerfile
    image: react-app-prod
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - mongodb_network    
volumes:
  mongodb_data:
    driver: local

networks:
  mongodb_network:
    driver: bridge
